# Generated by Django 2.2 on 2020-08-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vehicle_DateOfLastService',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='vehicle_DateOfPurchase',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='vehicle_VIN',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='vehicle_make',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='vehicle_model',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
