# Generated by Django 2.2 on 2020-08-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200822_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='vehicle_DateOfLastService',
            new_name='vehicle_date_of_last_service',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='vehicle_DateOfPurchase',
            new_name='vehicle_date_of_purchase',
        ),
    ]
