# Generated by Django 2.2 on 2020-08-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200822_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(default=' ', max_length=50)),
                ('vehicle_model', models.CharField(default=' ', max_length=50)),
                ('vehicle_VIN', models.CharField(default=' ', max_length=50)),
                ('vehicle_date_of_purchase', models.CharField(default=' ', max_length=50)),
                ('vehicle_date_of_last_service', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='vehicle_VIN',
        ),
        migrations.RemoveField(
            model_name='client',
            name='vehicle_date_of_last_service',
        ),
        migrations.RemoveField(
            model_name='client',
            name='vehicle_date_of_purchase',
        ),
        migrations.RemoveField(
            model_name='client',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='client',
            name='vehicle_model',
        ),
    ]
