# Generated by Django 2.2 on 2020-08-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_vehicle_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
